@startuml PosMgr

title 仓位更新流程

participant PosMgr
participant RM
participant TM
participant Gateway

== 启动时初始化仓位 ==
TM --> Gateway: query_positions
TM <-- Gateway: on_query_position(ticker_1)
RM <-- TM: on_query_position(ticker_1)
PosMgr <- RM: init_position(ticker_1)
...
TM --> Gateway: query_positions
TM <-- Gateway: on_query_position(ticker_n)
RM <-- TM: on_query_position(ticker_n)
PosMgr <- RM: init_position(ticker_n)

== 这里以订单发送成功为例 ==
RM <-- TM: check_order_req
PosMgr <- RM: check_order_req
PosMgr -> RM: NO_ERROR
RM --> RM: other checks (NO ERROR)
TM --> Gateway: send_order
TM <-- Gateway: success
RM <-- TM: on_order_sent
PosMgr <- RM: update_pending（pending增加）

== 收到拒单 ==
TM <-- Gateway: on_order_rejected
RM <-- TM: on_order_rejected
PosMgr <- RM: update_pending（pending减少）

== 收到成交回报 ==
TM <-- Gateway: on_order_traded
RM <-- TM: on_order_traded
PosMgr <- RM: update_traded

== 收到撤单回报 ==
TM <-- Gateway: on_order_canceled
RM <-- TM: on_order_canceled
PosMgr <- RM: update_pending（pending减少）

@enduml
