@startuml Trading

participant Strategy
participant Redis
participant TradingManagement
participant RiskManagement
participant Gateway
participant Exchange

== 订单被风控模块拒单 ==
Strategy -> Redis: publish order req
Redis -> TradingManagement: push order req
TradingManagement -> RiskManagement: check order req
TradingManagement <- RiskManagement: failure
TradingManagement -> RiskManagement: on order rejected
Redis <- TradingManagement: publish order rsp
Strategy <- Redis: push order rsp
Strategy -> Strategy: on order rsp(rejected by RM)

== 调用API发单失败 ==
Strategy -> Redis: publish order req
Redis -> TradingManagement: push order req
TradingManagement -> RiskManagement: check order req
TradingManagement <- RiskManagement: success
TradingManagement -> Gateway: send order
TradingManagement <- Gateway: fail to send
TradingManagement -> RiskManagement: on order rejcted
Redis <- TradingManagement: publish order rsp
Strategy <- Redis: push order rsp
Strategy -> Strategy: on order rsp(fail to send)

== 订单发送成功但被拒单 ==
Strategy -> Redis: publish order req
Redis -> TradingManagement: push order req
TradingManagement -> RiskManagement: check order req
TradingManagement <- RiskManagement: success
TradingManagement -> Gateway: send order
Gateway -> Exchange: send order successfully
TradingManagement <- Gateway: success
TradingManagement -> RiskManagement: on order sent
Gateway <- Exchange: order rejected
TradingManagement <- Gateway: order rejected
TradingManagement -> RiskManagement: on order rejected
Redis <- TradingManagement: publish order rsp
Strategy <- Redis: push order rsp
Strategy -> Strategy: on order rsp(rejected by server)


== 订单发送成功且被接受 ==
Strategy -> Redis: publish order req
Redis -> TradingManagement: push order req
TradingManagement -> RiskManagement: check order req
TradingManagement <- RiskManagement: success
TradingManagement -> Gateway: send order
Gateway -> Exchange: send order successfully
TradingManagement <- Gateway: success
TradingManagement -> RiskManagement: on order sent
Gateway <- Exchange: order accepted
TradingManagement <- Gateway: on order accepted
TradingManagement -> RiskManagement: on order accepted
Redis <- TradingManagement: publish order rsp
Strategy <- Redis: push order rsp
Strategy -> Strategy: on order rsp(order accepted)

== 订单成交（部分成交） ==
Gateway <- Exchange: order traded
TradingManagement <- Gateway: on order traded
TradingManagement -> RiskManagement: on order traded
Redis <- TradingManagement: publish order rsp
Strategy <- Redis: push order rsp
Strategy -> Strategy: on order rsp(order traded)

== 订单成交（全部成交） ==
Gateway <- Exchange: order traded
TradingManagement <- Gateway: on order traded
TradingManagement -> RiskManagement: on order traded
Redis <- TradingManagement: publish order rsp
Strategy <- Redis: push order rsp
Strategy -> Strategy: on order rsp(order traded, complete)

== 剩余部分撤单 ==
Gateway <- Exchange: order canceled
TradingManagement <- Gateway: on order canceled
TradingManagement -> RiskManagement: on order canceled
Redis <- TradingManagement: publish order rsp
Strategy <- Redis: push order rsp
Strategy -> Strategy: on order rsp(order canceled, complete)

== 撤单被拒绝 ==
Gateway <- Exchange: order cancel rejected
TradingManagement <- Gateway: on order cancel rejected
TradingManagement -> RiskManagement: on order cancel rejected

@enduml